name: ed-digital-twin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - pyodbc
  - pip
  - pip:
      - dtaidistance
